School.Auth/Pages/Account/Create/Index.cshtml.cs
// Copyright (c) Duende Software. All rights reserved.
// See LICENSE in the project root for license information.

using Duende.IdentityServer;
using Duende.IdentityServer.Models;
using Duende.IdentityServer.Services;
using Duende.IdentityServer.Test;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace IdentityServerHost.Pages.Create;

[SecurityHeaders]
[AllowAnonymous]
public class Index : PageModel
{
    private readonly TestUserStore _users;
    private readonly IIdentityServerInteractionService _interaction;

    [BindProperty]
    public InputModel Input { get; set; } = default!;

    public Index(
        IIdentityServerInteractionService interaction,
        TestUserStore? users = null)
    {
        // this is where you would plug in your own custom identity management library (e.g. ASP.NET Identity)
        _users = users ?? throw new InvalidOperationException("Please call 'AddTestUsers(TestUsers.Users)' on the IIdentityServerBuilder in Startup or remove the TestUserStore from the AccountController.");
            
        _interaction = interaction;
    }

    public IActionResult OnGet(string? returnUrl)
    {
        Input = new InputModel { ReturnUrl = returnUrl };
        return Page();
    }
        
    public async Task<IActionResult> OnPost()
    {
        // check if we are in the context of an authorization request
        var context = await _interaction.GetAuthorizationContextAsync(Input.ReturnUrl);

        // the user clicked the "cancel" button
        if (Input.Button != "create")
        {
            if (context != null)
            {
                // if the user cancels, send a result back into IdentityServer as if they 
                // denied the consent (even if this client does not require consent).
                // this will send back an access denied OIDC error response to the client.
                await _interaction.DenyAuthorizationAsync(context, AuthorizationError.AccessDenied);

                // we can trust model.ReturnUrl since GetAuthorizationContextAsync returned non-null
                if (context.IsNativeClient())
                {
                    // The client is native, so this change in how to
                    // return the response is for better UX for the end user.
                    return this.LoadingPage(Input.ReturnUrl);
                }

                return Redirect(Input.ReturnUrl ?? "~/");
            }
            else
            {
                // since we don't have a valid context, then we just go back to the home page
                return Redirect("~/");
            }
        }

        if (_users.FindByUsername(Input.Username) != null)
        {
            ModelState.AddModelError("Input.Username", "Invalid username");
        }

        if (ModelState.IsValid)
        {
            var user = _users.CreateUser(Input.Username, Input.Password, Input.Name, Input.Email);

            // issue authentication cookie with subject ID and username
            var isuser = new IdentityServerUser(user.SubjectId)
            {
                DisplayName = user.Username
            };

            await HttpContext.SignInAsync(isuser);

            if (context != null)
            {
                if (context.IsNativeClient())
                {
                    // The client is native, so this change in how to
                    // return the response is for better UX for the end user.
                    return this.LoadingPage(Input.ReturnUrl);
                }

                // we can trust Input.ReturnUrl since GetAuthorizationContextAsync returned non-null
                return Redirect(Input.ReturnUrl ?? "~/");
            }

            // request for a local page
            if (Url.IsLocalUrl(Input.ReturnUrl))
            {
                return Redirect(Input.ReturnUrl);
            }
            else if (string.IsNullOrEmpty(Input.ReturnUrl))
            {
                return Redirect("~/");
            }
            else
            {
                // user might have clicked on a malicious link - should be logged
                throw new ArgumentException("invalid return URL");
            }
        }

        return Page();
    }
}

School.Auth/Pages/Roles/Create.cshtml.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.ComponentModel.DataAnnotations;

namespace School.Auth.Pages.Roles
{
    [IgnoreAntiforgeryToken]
    public class CreateModel : AdminPageModel
    {
        private RoleManager<IdentityRole> roleManager;

        [BindProperty]
        [Required]
        public string Name { get; set; }

        public CreateModel(RoleManager<IdentityRole> roleManager)
        {
            this.roleManager = roleManager;
        }

        public async Task<IActionResult> OnPostAsync()
        {
            if (ModelState.IsValid)
            {
                IdentityRole role = new IdentityRole { Name = Name };
                IdentityResult result = await roleManager.CreateAsync(role);
                if (result.Succeeded)
                {
                    return RedirectToPage("List");
                }
                foreach (IdentityError err in result.Errors)
                {
                    ModelState.AddModelError("", err.Description);
                }
            }
            return Page();
        }
    }
}

School.Auth/Pages/Students/Editor.cshtml.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using School.Auth.Models;
using School.Domain;
using System.Text.Json;

namespace School.Auth.Pages.Students
{
    [IgnoreAntiforgeryToken]
    public class EditorModel : CoachPageModel
    {
        private UserManager<IdentityUser> userManager;

        public IdentityUser? Student { get; set; }
        public string ids { get; set; }
        public StudentIdsVm Ids { get; set; }

        public EditorModel(UserManager<IdentityUser> userManager)
        {
            this.userManager = userManager;
        }

        public IEnumerable<StudentCourseLookupDto> Purchased() =>
            Ids.studentsIds.FirstOrDefault(s => s.studentGuid == Student.Id)?.courses 
                ?? new List<StudentCourseLookupDto>();

        public IEnumerable<StudentCourseLookupDto> NonPurchased()
        {
            List<int> purchasedList = Purchased().Select(c => c.courseId).ToList() ?? new List<int>();
            return Ids.allCourses.Where(c => !purchasedList.Contains(c.courseId)).ToList();
        }

        public async Task OnGetAsync(string id, string ids)
        {
            this.ids = ids;
            this.Ids = JsonSerializer.Deserialize<StudentIdsVm>(this.ids);
            this.Student = await userManager.FindByIdAsync(id);
        }

        public async Task<IActionResult> OnPostAsync(int? courseid, string? studentid, string ids)
        {
            if (courseid is not null && !string.IsNullOrWhiteSpace(studentid))
            {
                this.Ids = JsonSerializer.Deserialize<StudentIdsVm>(ids);

                StudentCourseLookupDto course = Ids.allCourses.First(c => c.courseId == courseid);
                StudentLookupDto? student = Ids.studentsIds.FirstOrDefault(s => s.studentGuid == studentid);
                if (student != null)
                {
                    if (student.courses.Any(c => c.courseId == course.courseId))
                    {
                        RemoveStudentFromCourseDto dto = new RemoveStudentFromCourseDto
                        {
                            studentGuid = student.studentGuid,
                            courseId = course.courseId
                        };
                        return Redirect($"https://localhost:49824/students/from-course?dto={JsonSerializer.Serialize<RemoveStudentFromCourseDto>(dto)}");
                    }
                    else
                    {
                        AddStudentToCourseDto dto = new AddStudentToCourseDto
                        {
                            studentGuid = student.studentGuid,
                            courseId = course.courseId
                        };
                        return Redirect($"https://localhost:49824/students/to-course?dto={JsonSerializer.Serialize<AddStudentToCourseDto>(dto)}");
                    }
                }
                else
                {
                    IdentityUser studentUser = await userManager.FindByIdAsync(studentid);
                    AddStudentToCourseDto dto = new AddStudentToCourseDto
                    {
                        studentGuid = studentUser.Id,
                        courseId = course.courseId
                    };
                    return Redirect($"https://localhost:49824/students/to-course?dto={JsonSerializer.Serialize<AddStudentToCourseDto>(dto)}");
                }
            }
            return Page();
        }
    }
}

School.Auth/Pages/Students/List.cshtml.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using School.Auth.Models;
using System.Text.Json;

namespace School.Auth.Pages.Students
{
    [IgnoreAntiforgeryToken]
    public class ListModel : CoachPageModel
    {
        private UserManager<IdentityUser> userManager;

        public IEnumerable<IdentityUser> Students { get; set; }
        public string Search { get; set; }
        public string ids { get; set; }
        public StudentIdsVm Ids { get; set; }

        public ListModel(UserManager<IdentityUser> userManager)
        {
            this.userManager = userManager;
        }

        public async Task OnGetAsync(string ids, string search = "")
        {
            this.ids = ids;
            this.Ids = JsonSerializer.Deserialize<StudentIdsVm>(this.ids);

            if (!string.IsNullOrWhiteSpace(search))
            {
                Search = search;
                Students = (await userManager.GetUsersInRoleAsync("Student"))
                    .Where(u => u.Email != null && u.Email.ToLower().Contains(search.ToLower()));
            }
            else
            {
                var studentsIds = Ids.studentsIds.Select(s => s.studentGuid).ToList();
                Students = (await userManager.GetUsersInRoleAsync("Student")).Where(u => studentsIds.Contains(u.Id)).ToList();
            }
        }

        public IActionResult OnPostAsync(string search)
        {
            return RedirectToPage("List", new { search = search });
        }
    }
}

School.Auth/Pages/Users/List.cshtml.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace School.Auth.Pages.Users
{
    [IgnoreAntiforgeryToken]
    public class ListModel : AdminPageModel
    {
        private UserManager<IdentityUser> userManager;

        public IEnumerable<IdentityUser> Users { get; set; }
        public IEnumerable<string?> Roles { get; set; }

        public string Role { get; set; }
        public string SearchString { get; set; } = "";

        public ListModel(UserManager<IdentityUser> userManager, RoleManager<IdentityRole> roleManager)
        {
            this.userManager = userManager;
            Roles = roleManager.Roles.Select(r => r.Name).ToList();
        }

        public async Task OnGetAsync(string searchstring = "", string role = "All")
        {
            if (string.IsNullOrWhiteSpace(searchstring))
            {
                Role = role;
                if (Role == "All")
                    Users = userManager.Users.ToList();
                else
                    Users = (await userManager.GetUsersInRoleAsync(Role)).ToList();
            }
            else
            {
                Role = "All";
                SearchString = searchstring;
                Users = userManager.Users
                    .Where(u => u.Email != null && u.Email.ToLower().Contains(SearchString.ToLower()))
                    .ToList();
            }
        }

        public IActionResult OnPostAsync(string role)
        {
            return RedirectToPage("List", new { role = role });
        }

        public IActionResult OnPostSearchAsync(string searchstring)
        {
            return RedirectToPage("List", new { searchstring = searchstring });
        }

        public async Task<IActionResult> OnPostDeleteAsync(string id)
        {
            IdentityUser? user = await userManager.FindByIdAsync(id);
            if (user is not null)
            {
                await userManager.DeleteAsync(user);
            }
            return RedirectToPage();
        }
    }
}

School.Auth/Pages/Users/Create.cshtml
@page
@model School.Auth.Pages.Users.CreateModel
@{
    ViewData["Title"] = "Создание пользователя";
}

<div class="container">
    <h2 class="bg-primary text-center text-white p-1 mb-2">@ViewData["Title"]</h2>

    <form asp-page="/Users/Create" method="post">
        <div asp-validation-summary="All" class="text-danger"></div>

        <div class="form-group">
            <label asp-for="UserName">Имя пользователя</label>
            <input asp-for="UserName" class="form-control" value="@Model.UserName" />
        </div>

        <div class="form-group mt-3">
            <label asp-for="Email">Email</label>
            <input type="email" asp-for="Email" class="form-control" value="@Model.Email" />
        </div>

        <div class="form-group mt-3">
            <label asp-for="Phone">
                Номер телефона
                <small>Format: +79991112233</small>
            </label>
            <input type="tel" asp-for="Phone" class="form-control" value="@Model.Phone" pattern="\+7\d{10}" />
        </div>

        <div class="form-group mt-3">
            <label asp-for="Password">Пароль</label>
            <input type="password" asp-for="Password" class="form-control" value="@Model.Password" />
        </div>

        <div class="form-group mt-3">
            <label asp-for="ConfirmPassword">Подтверждение пароля</label>
            <input type="password" asp-for="ConfirmPassword" class="form-control" value="@Model.Password" />
        </div>

        <div class="form-group">
            <label asp-for="RoleId" class="control-label mt-3">Добавить роль?</label>
            <select asp-for="RoleId" asp-items="@(new SelectList(Model.Roles, "Id", "Name"))" class="form-control">
                <option value="" disabled selected>Без роли</option>
            </select>
        </div>

        <div class="container-fluid text-center mt-4 mb-5">
            <div class="form-group">
                <button type="submit" class="btn btn-primary">Сохранить</button>
                <a class="btn btn-secondary" asp-page="List">Назад</a>
            </div>
        </div>
    </form>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

School.Auth/Pages/Users/Editor.cshtml
@page "{id}"
@model School.Auth.Pages.Users.EditorModel
@{
    ViewData["Title"] = Model.UserName;
}

<div class="container">
    <h2 class="bg-primary text-center text-white p-1 mb-2">Редактирование пользователя: @ViewData["Title"]</h2>

    <form method="post">
        <div asp-validation-summary="All" class="text-danger"></div>

        <input name="Id" type="hidden" value="@Model.Id" />

        <div class="form-group mt-3">
            <label asp-for="UserName">Имя пользователя</label>
            <input asp-for="UserName" class="form-control" value="@Model.UserName" />
        </div>

        <div class="form-group mt-3">
            <label asp-for="Email">Email</label>
            <input type="email" asp-for="Email" class="form-control" value="@Model.Email" />
        </div>

        <div class="form-group mt-3">
            <label asp-for="Phone">
                Номер телефона
                <small>Format: +79991112233</small>
            </label>
            <input type="tel" asp-for="Phone" class="form-control" value="@Model.Phone" pattern="\+7\d{10}" />
        </div>

        <div class="form-group mt-3">
            <label asp-for="Password">Новый пароль (при необходимости)</label>
            <input type="password" asp-for="Password" class="form-control" value="@Model.Password" />
        </div>

        <div class="form-group mt-3">
            <label asp-for="ConfirmPassword">Подтверждение нового пароля (при необходимости)</label>
            <input type="password" asp-for="ConfirmPassword" class="form-control" value="@Model.Password" />
        </div>

        <div class="container-fluid text-center mt-4 mb-5">
            <div class="form-group">
                <button type="submit" class="btn btn-primary">Сохранить</button>
                <a class="btn btn-secondary" asp-page="List">Назад</a>
            </div>
        </div>
    </form>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

School.Auth/Pages/Users/List.cshtml
@page
@model School.Auth.Pages.Users.ListModel
@{
    ViewData["Title"] = "Пользователи";
}

<div class="container">
    <h2 class="bg-primary text-center text-white p-1 mb-2">@ViewData["Title"]</h2>

    <div class="mb-3">
        <form asp-page="List" asp-page-handler="Search" method="post">
            <div class="form-group">
                <label asp-for="SearchString">Поиск по Email среди всех пользователей:</label>
                <input type="search" asp-for="SearchString" class="form-control" placeholder="Поиск..." />
            </div>
        </form>
    </div>

    <form method="post">
        <select asp-for="Role" asp-items="@(new SelectList(Model.Roles))" class="form-select" onchange="this.form.submit()">
            <option>All</option>
        </select>
    </form>

    <table class="table table-sm table-bordered my-3">
        <thead>
            <tr class="text-center">
                <th>Имя</th>
                <th>Email</th>
                <th class="col-4"></th>
            </tr>
        </thead>
        <tbody>
            @if (Model.Users.Count() == 0)
            {
                <tr>
                    <td colspan="4" class="text-center">Нет пользователей</td>
                </tr>
            }
            else
            {
                foreach (IdentityUser user in Model.Users)
                {
                    <tr class="cell_justify">
                        <td>@user.UserName</td>
                        <td>@user.Email</td>
                        <td class="text-center">
                            <form asp-page="List" asp-page-handler="Delete" method="post">
                                <input type="hidden" name="Id" value="@user.Id" />
                                <a class="btn btn-sm btn-primary mx-2" asp-page="Editor" asp-route-id="@user.Id" asp-route-mode="edit">Редактировать</a>
                                <button type="submit" class="btn btn-sm btn-danger mx-2">Удалить</button>
                            </form>
                        </td>
                    </tr>
                }
            }
        </tbody>
    </table>

    <div class="text-center mb-5">
        <a class="btn btn-primary" asp-page="Create">Создать</a>
    </div>
</div>